# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8acd3c9c31fd37a66d48e5935ec4a9a174fbfb516b4972dfb06276c24d8a1b9baf4ca707715b22f4d8438dbf8812b8e5e74ef7b82568045127b8cbd0c6a87bfe

test:
  secret_key_base: 70c886419386c7927b0d5cf09d18c337c1496007b8fc14f3a642208030e11b45cf4c0e300a640f8d519d2e7e4eaee226ea3f385d18deb5f9a65ab99f53c71aee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
